// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NCBlog.Repository.DbContext;

namespace NCBlog.Repository.Migrations
{
    [DbContext(typeof(NCBlogDbContext))]
    partial class NCBlogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NCBlog.Model.UserTypes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TypeName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("UserTypeses");
                });

            modelBuilder.Entity("NCBlog.Model.WriteBlog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApprovedBy");

                    b.Property<DateTime>("ApprovedDate");

                    b.Property<DateTime>("BlogCreateDate");

                    b.Property<string>("BlogDescription");

                    b.Property<string>("BlogTitle");

                    b.Property<int>("BlogWriterId");

                    b.Property<string>("DeleteBy");

                    b.Property<DateTime>("DeleteDate");

                    b.Property<bool>("IsApproved");

                    b.Property<int>("IsDelete");

                    b.Property<bool>("IsPublished");

                    b.Property<DateTime>("PublishedDate");

                    b.Property<string>("UpdateBy");

                    b.Property<DateTime>("UpdateDate");

                    b.HasKey("Id");

                    b.ToTable("WriteBlogs");
                });
#pragma warning restore 612, 618
        }
    }
}
